// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkShop.IO.Infra.Client.Context;

namespace WorkShop.IO.Infra.Client.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20180725131735_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WorkShop.Client.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CascadeMode");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Identification");

                    b.Property<DateTime>("LastInteraction");

                    b.Property<string>("Password");

                    b.Property<Guid?>("UserLoggedId");

                    b.HasKey("Id");

                    b.HasIndex("Identification")
                        .IsUnique();

                    b.HasIndex("UserLoggedId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WorkShop.Client.UserLogged", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CascadeMode");

                    b.Property<DateTime>("DataCheck");

                    b.Property<DateTime>("DataLogged");

                    b.Property<string>("Hash");

                    b.Property<string>("Ip");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserLogged");
                });

            modelBuilder.Entity("WorkShop.Client.User", b =>
                {
                    b.HasOne("WorkShop.Client.UserLogged")
                        .WithMany("User")
                        .HasForeignKey("UserLoggedId");
                });
#pragma warning restore 612, 618
        }
    }
}
